IPLAuction/Controllers/Content View Controllers/SeasonViewController.cs
using IPLAuction.Models;
using IPLAuction.Models.Extended;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IPLTrial.Controllers
{
    public class SeasonViewController : Controller
    {

        IPLEntities ipl = new IPLEntities();
        PlayerUtility play_util = new PlayerUtility();


        // GET: SeasonView
        public ActionResult SeasonView()
        {
            Response.Cache.SetNoStore();

            using (var context = new IPLEntities())
            {

                ViewBag.count_matches = context.match_master.ToList().Count;
                ViewBag.count_players = context.player_master.ToList().Count;
                ViewBag.count_teams = context.team_master.ToList().Count;

                int id = Convert.ToInt32(System.Web.HttpContext.Current.Session["userID"]);
                if (id != 0)
                {
                    ViewBag.user_id = id;

                    string user_name = System.Web.HttpContext.Current.Session["user_name"].ToString();
                    ViewBag.user_name = user_name;
                    TempData["user_name"] = ViewBag.user_name;

                    string user_type = System.Web.HttpContext.Current.Session["user_type"].ToString();
                    ViewBag.user_type = user_type;
                    TempData["user_type"] = ViewBag.user_type;

                    ViewBag.user_image = System.Web.HttpContext.Current.Session["user_image"];
                    TempData["user_image"] = ViewBag.user_image;

                }
            }

            return View();
        }


        public ActionResult GetSeasons()
        {

            //ipl.Configuration.ProxyCreationEnabled = false;

            var season = new
            {
                data =

                (from s in ipl.season_master.DefaultIfEmpty()

                join p in ipl.player_master on s.orange_cap_player_id equals p.player_id into pMap
                join p1 in ipl.player_master on s.purple_cap_player_id equals p1.player_id into pMap1
                 join p2 in ipl.player_master on s.man_series_player_id equals p2.player_id  into pMap2

                 from p in pMap.DefaultIfEmpty()
                 from p1 in pMap1.DefaultIfEmpty()
                 from p2 in pMap2.DefaultIfEmpty()

                 where s.season_year != 0
                 select new
                {
                    s.season_id,
                    s.season_year,
                    orange = p.player_id.ToString() == null ? String.Empty : p.player_name,
                    purple = p1.player_id.ToString() == null ? String.Empty : p1.player_name,
                    man = p2.player_id.ToString() == null ? String.Empty : p2.player_name,
                    s.sixes_count,
                    s.catches_count
                }).ToList()
            };
            return Json(season, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Save(int id)
        {
            ViewBag.players = play_util.GetAllActivePlayers();
            using (IPLEntities ipl = new IPLEntities())
            { 

                var v = ipl.season_master.Where(s => s.season_id == id).FirstOrDefault();
                TempData["players"] = ViewBag.players;
                return PartialView(v);
            }
        }

        [HttpPost]
        public ActionResult Save(season_master season)
        {
            bool status = false;
            

            if(season.man_series_player_id == null)
            {
                return new JsonResult { Data = new { status = status } };
            }
            if(season.orange_cap_player_id == null)
            {
                return new JsonResult { Data = new { status = status } };
            }
            if(season.purple_cap_player_id == null)
            {
                return new JsonResult { Data = new { status = status } };
            }

            if(season.catches_count <= 300 && season.sixes_count <= 300)
            {
                return new JsonResult { Data = new { status = status } };
            }

            if (ModelState.IsValid)
            {
                using (IPLEntities ipl = new IPLEntities())
                {
                    if (season.season_id > 0)
                    {
                        //Edit
                        var v = ipl.season_master.Where(a => a.season_id == season.season_id).FirstOrDefault();
                        if (v != null)
                        {
                            v.man_series_player_id = season.man_series_player_id;
                            v.orange_cap_player_id = season.orange_cap_player_id;
                            v.purple_cap_player_id = season.purple_cap_player_id;
                            v.season_year = season.season_year;
                            v.sixes_count = season.sixes_count;
                            v.catches_count = season.catches_count;
                        }
                    }
                    else
                    {
                        //Save
                        ipl.season_master.Add(season);
                    }
                    ipl.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

        public ActionResult Delete(int id)
        {
            using(IPLEntities ipl = new IPLEntities())
            {
                var v = ipl.season_master.Where(a => a.season_id == id).FirstOrDefault();
                if (v != null)
                {
                    //return View(v);
                    return PartialView(v);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }

        [HttpPost]
        //[ActionName("Delete")]
        public ActionResult Delete(int id, season_master season)
        {
            bool status = false;
            using (IPLEntities ipl = new IPLEntities())
            {
                var v = ipl.season_master.Where(a => a.season_id == id).FirstOrDefault();
                if(v!= null)
                {
                    ipl.season_master.Remove(v);
                    ipl.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }
    }
}

IPLAuction/Views/SeasonView/Delete.cshtml
@model IPLAuction.Models.season_master
<h2>Delete Season</h2>
@using (Html.BeginForm("Delete", "SeasonView", FormMethod.Post, new { id = "popupForm" }))
{


     @Html.HiddenFor(a => a.season_id)

        <div class="form-group">
            <label>Season Year</label>
            <p>@Model.season_year</p>
        </div>
        <div class="form-group">
            <label>Orange Cap</label>
            <p>@Model.orange_cap_player_id</p>
        </div>

        <div class="form-group">
            <label>Purple Cap</label>
            <p>@Model.purple_cap_player_id</p>
        </div>

        <div class="form-group">
            <label>Man of the series</label>
            <p>@Model.man_series_player_id</p>
        </div>

        <div class="form-group">
            <label>Sixes Count</label>
            <p>@Model.sixes_count</p>
        </div>

        <div>
            <input type="submit" value="Submit">
        </div>
}


IPLAuction/Views/SeasonView/Save.cshtml
@model IPLAuction.Models.season_master
<h2>Edit Season</h2>
@using (Html.BeginForm("Save", "SeasonView", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model != null && Model.season_id > 0)
    {
       
            @Html.HiddenFor(a=>a.season_id)

        <div class="form-group">
            <label>Season Year</label>
            @Html.TextBoxFor(a => a.season_year, new { @class = "form-control", @readonly="readonly" })
        </div>

        <div class="form-group">
            <label>Orange Cap</label>
            @Html.DropDownListFor(a => a.orange_cap_player_id, TempData["players"] as List<SelectListItem>, "", new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Purple Cap</label>
            @Html.DropDownListFor(a => a.purple_cap_player_id, TempData["players"] as List<SelectListItem>, "", new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Man of the Match</label>
            @Html.DropDownListFor(a => a.man_series_player_id, TempData["players"] as List<SelectListItem>, "", new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Sixes</label>
            @Html.TextBoxFor(a => a.sixes_count, new { @class = "form-control", @type="number" })
        </div>

        <div class="form-group">
            <label>Catches</label>
            @Html.TextBoxFor(a => a.catches_count, new { @class = "form-control", @type = "number" })
        </div>
        <div>
            <input type="submit" value="Submit">
        </div>
    }

}

IPLAuction/Views/SeasonView/SeasonView.cshtml
@{
    ViewBag.Title = "SeasonView";
     Layout = "~/Views/Shared/_LayoutGentelella.cshtml";
}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Edit Season Details</title>
    <link href="~/Content/DataTables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="~/Scripts/alertify.js-0.3.11/themes/alertify.core.css" rel="stylesheet" />
    <link href="~/Scripts/alertify.js-0.3.11/themes/alertify.default.css" rel="stylesheet" />
    <style>
        .error {
            color: red;
        }

        .dataTables_wrapper {
            color: black;
            font-size: 13px;
        }
    </style>
</head>

<body>

    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">

            <div class="page-title">
                <div class="title_left">
                    <h3>Edit Season Details</h3><br><br>
                </div>
            </div>

            <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
            <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
            <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.16/r-2.2.0/datatables.min.js"></script>
            <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
            <script src="~/Scripts/alertify.js-0.3.11/src/alertify.js"></script>

            <div class="tablecontainer" style="width:100%; margin: 0 auto;">
                <table id="myDatatable" class="table table-striped table-bordered display nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Season Year</th>
                            <th>Orange Cap</th>
                            <th>Purple Cap</th>
                            <th>Man of the Season</th>
                            <th>Sixes</th>
                            <th>Catches</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                </table>
            </div>

            <!-- / Page Content-->


            <script>

                $(document).ready(function () {

                    var bootstrapButton = $.fn.button.noConflict() // return $.fn.button to previously assigned value
                    $.fn.bootstrapBtn = bootstrapButton            // give $().bootstrapBtn the Bootstrap functionality

                //for datatable

                    var oTable = $('#myDatatable').DataTable({
                        responsive: true,
                        "ajax": {
                            "processing": true,
                            "url": '@Url.Action("GetSeasons")',
                            "type": "GET",
                            "datatype": "json"
                        },

                        "columns": [
                            { "data": "season_year", "name": "season_year", "autoWidth": true, "searchable": true },

                            { "data": "orange", "name": "player_name", "autoWidth": true },

                            { "data": "purple", "name": "player_name", "autoWidth": true },

                            { "data": "man", "name": "player_name", "autoWidth": true },

                            { "data": "sixes_count", "name": "sixes_count", "autoWidth": true },

                            { "data": "catches_count", "name": "catches_count", "autoWidth": true },

                            {

                                "data": "season_id", "width": "50px", "render": function (data) {
                                    return '<a class="popup" href="/SeasonView/Save/' + data + '">Edit</a>';
                                }
                            },
                            {

                                "data": "season_id", "width": "50px", "render": function (data) {
                                    return '<a class="popup"  href="/SeasonView/Delete/' + data + '">Delete</a>';

                                }
                            }
                        ],

                        "columnDefs": [{
                            "targets": [2, 3, 4],
                            "orderable": false
                        }],

                    });

                    $('.tablecontainer').on('click', 'a.popup', function (e) {

                        e.preventDefault();
                        OpenPopup($(this).attr('href'));
                    })

                    function OpenPopup(pageUrl) {
                        var $pageContent = $('<div/>');
                        $pageContent.load(pageUrl, function () {
                            $('#popupForm', $pageContent).removeData('validator');
                            $('#popupForm', $pageContent).removeData('unobtrusiveValidation');
                            $.validator.unobtrusive.parse('form');
                        });

                        $dialog = $('<div class = "popupWindow" style="overflow:auto;"></div>')
                            .html($pageContent)
                            .dialog({
                                draggable: false,
                                autoOpen: false,
                                resizable: false,
                                model: true,
                                title: 'Season View',
                                height: 550,
                                width: 600,
                                close: function () {
                                    $dialog.dialog('destroy').remove();
                                }
                            })

                        $('.popupWindow').on('submit', '#popupForm', function (e) {
                            var url = $('#popupForm')[0].action;
                            $.ajax({
                                type: "POST",
                                url: url,
                                data: $('#popupForm').serialize(),
                                success: function (data) {
                                    var s = data.status;
                                    if (s == true) {
                                        $dialog.dialog('close');
                                        alertify.success("Updated successfully!");
                                        oTable.ajax.reload();
                                    }
                                    else {
                                        $dialog.dialog('close');
                                        alertify.error("Some error occurred!");
                                        oTable.ajax.reload();
                                    }
                                   
                                }
                            })
                            e.preventDefault();
                        })
                        $dialog.dialog('open');
                    }
                });
            </script>

        </div>
    </div>
</body>

</html>