IPLAuction/Models/player_master.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPLAuction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public player_master()
        {
            this.player_skills = new HashSet<player_skills>();
            this.match_master = new HashSet<match_master>();
        }
    
        public int player_id { get; set; }
        public string player_name { get; set; }
        public System.DateTime player_dob { get; set; }
        public int player_batting_style { get; set; }
        public int player_bowling_skill { get; set; }
        public int country { get; set; }
        public string player_image { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> selected { get; set; }
        public Nullable<bool> sold_out { get; set; }
        public Nullable<int> player_image_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<player_skills> player_skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<match_master> match_master { get; set; }
    }
}

IPLAuction/Controllers/Master/PlayerMasterController.cs
using IPLAuction.Models;
using IPLAuction.Models.Extended;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IPLTrial.Controllers
{
    public class PlayerMasterController : Controller
    {
        PlayerUtility pu = new PlayerUtility();
        IPLEntities ipl = new IPLEntities();
        TeamUtility teamUtility = new TeamUtility();

        // GET: PlayerMaster
        public ActionResult AddPlayer()
        {

            ViewBag.batting = pu.GetBattingStyle();
            ViewBag.bowling = pu.GetBowlingSkills();
            ViewBag.country = pu.GetCountryList();
            Response.Cache.SetNoStore();

            using (var context = new IPLEntities())
            {

                ViewBag.count_matches = context.match_master.ToList().Count;
                ViewBag.count_players = context.player_master.ToList().Count;
                ViewBag.count_teams = context.team_master.ToList().Count;

                int id = Convert.ToInt32(System.Web.HttpContext.Current.Session["userID"]);
                if (id != 0)
                {
                    ViewBag.user_id = id;

                    string user_name = System.Web.HttpContext.Current.Session["user_name"].ToString();
                    ViewBag.user_name = user_name;
                    TempData["user_name"] = ViewBag.user_name;

                    string user_type = System.Web.HttpContext.Current.Session["user_type"].ToString();
                    ViewBag.user_type = user_type;
                    TempData["user_type"] = ViewBag.user_type;

                    ViewBag.user_image = System.Web.HttpContext.Current.Session["user_image"];
                    TempData["user_image"] = ViewBag.user_image;

                }
                else
                {
                    TempData["user_image"] = "/uploads/default-user-image.png";
                }
            }

            return View();
        }


        [HttpPost]
        public ActionResult AddPlayer(player_master player, player_skills skill, System.Web.HttpPostedFileBase fileUpload)

        {
            ViewBag.batting = pu.GetBattingStyle();
            ViewBag.bowling = pu.GetBowlingSkills();
            ViewBag.country = pu.GetCountryList();

            if (fileUpload != null && fileUpload.ContentLength > 0)
            {
                //extract file name
                var fileName = Path.GetFileName(fileUpload.FileName);
                //store the file inside ~/App_Data/uploads folder
                var path = Path.Combine(Server.MapPath("~/uploads/"), fileName);
                fileUpload.SaveAs(path);


                if (ModelState.IsValid)
                {
                    player.selected = false;
                    player.player_image = Url.Content("~/uploads/" + fileName);

                    ipl.player_master.Add(player);


                    /*Base Fare calculation*/
                    var base_price = 50000;
                    var batting_star = skill.player_batting_star;
                    var bowling_star = skill.player_bowling_star;
                    switch (batting_star)
                    {
                        case 1: base_price += 0;
                            break;
                        case 2: base_price += 10000;
                            break;
                        case 3: base_price += 20000;
                            break;
                        case 4: base_price += 30000;
                            break;
                        case 5: base_price += 45000;
                            break;
                    }
                    switch (bowling_star)
                    {
                        case 1:
                            base_price += 7000;
                            break;
                        case 2:
                            base_price += 13000;
                            break;
                        case 3:
                            base_price += 24000;
                            break;
                        case 4:
                            base_price += 38000;
                            break;
                        case 5:
                            base_price += 49000;
                            break;
                    }

                    skill.player_base_price = base_price;
                    skill.player_master = player;

                    ipl.player_skills.Add(skill);
                    ipl.SaveChanges();
                    player.player_image_id = player.player_id;
                    ipl.SaveChanges();

                    ViewBag.Added = true;
                    ViewBag.new_player_name = player.player_name;

                    ModelState.Clear();
                    return View();
                }
                else
                {
                    ViewBag.Success = false;
                }
            }

            return View();
        }

        //get View: Battingskill
        public ActionResult NewBattingSkill()
        {


            Response.Cache.SetNoStore();

            using (var context = new IPLEntities())
            {

                ViewBag.count_matches = context.match_master.ToList().Count;
                ViewBag.count_players = context.player_master.ToList().Count;
                ViewBag.count_teams = context.team_master.ToList().Count;

                int id = Convert.ToInt32(System.Web.HttpContext.Current.Session["userID"]);
                if (id != 0)
                {
                    ViewBag.user_id = id;

                    string user_name = System.Web.HttpContext.Current.Session["user_name"].ToString();
                    ViewBag.user_name = user_name;
                    TempData["user_name"] = ViewBag.user_name;

                    string user_type = System.Web.HttpContext.Current.Session["user_type"].ToString();
                    ViewBag.user_type = user_type;
                    TempData["user_type"] = ViewBag.user_type;

                    ViewBag.user_image = System.Web.HttpContext.Current.Session["user_image"];
                    TempData["user_image"] = ViewBag.user_image;

                }
                else
                {
                    TempData["user_image"] = "/uploads/default-user-image.png";
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult NewBattingSkill(bowling_skill_master bowling)
        {

            Response.Cache.SetNoStore();
            if (ModelState.IsValid)
            {

                var query = ipl.bowling_skill_master.Where(a => a.bowling_skill == bowling.bowling_skill).Select(a => a.bowling_skill).FirstOrDefault();
                if (query != null)
                {
                    ViewBag.Success_Bowling_Validate = false;
                }
                else
                {
                    ipl.bowling_skill_master.Add(bowling);
                    ipl.SaveChanges();
                    ViewBag.Added_Bowling = true;

                    ModelState.Clear();
                    return View();
                }
            }
            else
            {
                ViewBag.Success_Bowling = false;
            }

            return View();
        }

        //get View: new country
        public ActionResult NewCountry()
        {

            Response.Cache.SetNoStore();

            using (var context = new IPLEntities())
            {

                ViewBag.count_matches = context.match_master.ToList().Count;
                ViewBag.count_players = context.player_master.ToList().Count;
                ViewBag.count_teams = context.team_master.ToList().Count;

                int id = Convert.ToInt32(System.Web.HttpContext.Current.Session["userID"]);
                if (id != 0)
                {
                    ViewBag.user_id = id;

                    string user_name = System.Web.HttpContext.Current.Session["user_name"].ToString();
                    ViewBag.user_name = user_name;
                    TempData["user_name"] = ViewBag.user_name;

                    string user_type = System.Web.HttpContext.Current.Session["user_type"].ToString();
                    ViewBag.user_type = user_type;
                    TempData["user_type"] = ViewBag.user_type;

                    ViewBag.user_image = System.Web.HttpContext.Current.Session["user_image"];
                    TempData["user_image"] = ViewBag.user_image;

                }
                else
                {
                    TempData["user_image"] = "/uploads/default-user-image.png";
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult NewCountry(country_master country)
        {
            Response.Cache.SetNoStore();
            if (ModelState.IsValid)
            {

                var query = ipl.country_master.Where(a => a.country_name == country.country_name).Select(a => a.country_name).FirstOrDefault();
                if (query != null)
                {
                    ViewBag.Success_Country_Validate = false;
                }
                else
                {
                    ipl.country_master.Add(country);
                    ipl.SaveChanges();
                    ViewBag.Added_Country = true;

                    ModelState.Clear();
                    return View();
                }
            }
            else
            {
                ViewBag.Success_Country = false;
            }

            return View();
        }


IPLAuction/Views/PlayerMaster/AddPlayer.cshtml
@model IPLAuction.Models.Validation.player_masterMetaData
@{

    ViewBag.Title = "AddPlayer";
     Layout = "~/Views/Shared/_LayoutGentelella.cshtml";
}

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Add New Player</title>
    <link href="~/Content/css/icheck/flat/green.css" rel="stylesheet">
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <link href="~/Content/themes/base/datepicker.css" rel="stylesheet" />
    <style>
        .error {
            color: #ef5350;
        }
    </style>
</head>
<body>
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">

            <div class="page-title">
                <div class="title_left">
                    <h3>New Player</h3>
                </div>
            </div>


            @using (Html.BeginForm("AddPlayer", "PlayerMaster",
                FormMethod.Post,
                 new { enctype = "multipart/form-data", @class = "form-horizontal form-label-left", style = "margin-right:200px; margin-top:60px;" }))

            {

                <div class="form-group">
                    @Html.LabelFor(a => a.player_name, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.TextBoxFor(a => a.player_name, new { @class = "form-control col-md-7 col-xs-12", type = "text", @autocomplete = "off" })
                        @Html.ValidationMessageFor(a => a.player_name, "", new { @class = "error" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(a => a.player_dob, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-3 col-sm-3 col-xs-6">
                        @Html.TextBoxFor(a => a.player_dob, new { @class = "form-control datepicker", placeholder = "Select Date Of Birth...", id = "dob", @required = "required", @autocomplete = "off" })
                        @Html.ValidationMessageFor(a => a.player_dob, "", new { @class = "error" })
                    </div>
                </div>


                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Batting Style<span class="required">*</span></label>
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.DropDownListFor(a => a.player_batting_style, ViewBag.batting as List<SelectListItem>, "--Choose batting style--", new { @class = "select2_single form-control" })
                        @Html.ValidationMessageFor(a => a.player_batting_style, "", new { @class = "error" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Batting star<span class="required">*</span></label>
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.DropDownListFor(a => a.player_batting_star,
                 new List<SelectListItem>
                 {
                           new SelectListItem{Text="1", Value="1"},
                           new SelectListItem{Text="2", Value="2"},
                           new SelectListItem{Text="3", Value="3"},
                           new SelectListItem{Text="4", Value="4"},
                           new SelectListItem{Text="5", Value="5"},

                 }, "--Select batting stars--", new { @class = "select2_single form-control", @name = "drpBattingStar" })
                        @Html.ValidationMessageFor(a => a.player_batting_star, "", new { @class = "error" })
                    </div>
                </div>



                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Bowling Style<span class="required">*</span></label>
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.DropDownListFor(a => a.player_bowling_skill, ViewBag.bowling as List<SelectListItem>, "--Choose bowling skill--", new { @class = "select2_single form-control" })
                        @Html.ValidationMessageFor(a => a.player_bowling_skill, "", new { @class = "error" })
                    </div>
                </div>



                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Bowling star<span class="required">*</span></label>
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.DropDownListFor(a => a.player_bowling_star,
                 new List<SelectListItem>
                 {
                           new SelectListItem{Text="1", Value="1"},
                           new SelectListItem{Text="2", Value="2"},
                           new SelectListItem{Text="3", Value="3"},
                           new SelectListItem{Text="4", Value="4"},
                           new SelectListItem{Text="5", Value="5"},

                 }, "--Select bowling stars--", new { @class = "select2_single form-control", @name = "drpBowlingStar" })
                        @Html.ValidationMessageFor(a => a.player_bowling_star, "", new { @class = "error" })
                    </div>
                </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Nationality<span class="required">*</span></label>
                            <div class="col-md-4 col-sm-4 col-xs-6">
                                @Html.DropDownListFor(a => a.country, ViewBag.country as List<SelectListItem>, "--Choose nationality--", new { @class = "select2_single form-control" })
                                @Html.ValidationMessageFor(p => p.country, "", new { @class = "error" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(a => a.active, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-4 col-sm-4 col-xs-6">
                                @Html.RadioButtonFor(a => a.active, true, new { @class = "flat", @checked = "checked" })
                                <label for="Active">Active</label>

                                @Html.RadioButtonFor(a => a.active, false, new { @class = "flat"})
                                <label for="Inactive">Inactive</label><br />
                                @Html.ValidationMessageFor(a => a.active, "", new { @class = "error" })
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(a => a.player_image, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-4 col-sm-4 col-xs-6">
                                <input type="file" name="fileUpload" class="form-control col-md-7 col-xs-12" required="required" />
                            </div>
                            @Html.ValidationMessageFor(a => a.player_image, "", new { @class = "error" })
                        </div>


                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="reset" class="btn btn-primary">Cancel</button>
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </div>
            }

            <script type="text/javascript">
                            $(function () { // will trigger when the document is ready
                                $('#dob').datepicker({
                                    dateFormat: 'yy-mm-dd',
                                    changeMonth: true,
                                    changeYear: true,
                                    yearRange: "1985:2000"
                                   
                                }); //Initialise any date pickers
                                
                });
                $('a.dropdown-toggle, .dropdown-menu a').on('touchstart', function (e) {
                    e.stopPropagation();
                });
            </script>


            @if (ViewBag.Success == false)
            {
                <div class="alert alert-error alert-dismissable fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Error!</strong> Fill in the required details!
                </div>
            }

            @if (ViewBag.Added == true)
            {
                <div class="alert alert-info alert-dismissable fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Success!</strong> @ViewBag.new_player_name was added successfully!
                </div>
            }

        </div>
    </div>


</body>
</html>

IPLAuction/Views/PlayerMaster/NewBattingSkill.cshtml
@model IPLAuction.Models.bowling_skill_master

@{
    ViewBag.Title = "NewBattingSkill";
    Layout = "~/Views/Shared/_LayoutGentelella.cshtml";
}

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Add New Player</title>
    <link href="~/Content/css/icheck/flat/green.css" rel="stylesheet">
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <link href="~/Content/themes/base/datepicker.css" rel="stylesheet" />
    <style>
        .error {
            color: #ef5350;
        }
    </style>
</head>
<body>

    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">

            <div class="page-title">
                <div class="title_left">
                    <h3>New Bowling Skill</h3>
                </div>
            </div>


            @using (Html.BeginForm("NewBattingSkill", "PlayerMaster",
                FormMethod.Post,
                 new { enctype = "multipart/form-data", @class = "form-horizontal form-label-left", style = "margin-right:200px; margin-top:60px;" }))

            {


                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">New Bowling Skill<span class="required">*</span></label>
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.TextBoxFor(a => a.bowling_skill, new { @class = "form-control col-md-7 col-xs-12", type = "text", name="txtSkill", @autocomplete = "off", required = "required" })
                        @Html.ValidationMessageFor(a => a.bowling_skill, "", new { @class = "error" })
                    </div>
                </div>

                <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="reset" class="btn btn-primary">Cancel</button>
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </div>
            }

            @if (ViewBag.Success_Bowling == false)
            {
                <div class="alert alert-error alert-dismissable fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Error!</strong> Fill in the required details!
                </div>
            }

            @if (ViewBag.Success_Bowling_Validate == false)
            {
                <div class="alert alert-error alert-dismissable fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Error!</strong> Entered Bowling Skill already exists!
                </div>
            }

            @if (ViewBag.Added_Bowling == true)
            {
                <div class="alert alert-info alert-dismissable fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Success!</strong> New Bowling Style Added Successfully!
                </div>
            }

        </div>
    </div>


</body>
</html>

IPLAuction/Views/PlayerMaster/NewCity.cshtml
@model IPLAuction.Models.city_master

@{
    ViewBag.Title = "NewCity";
    Layout = "~/Views/Shared/_LayoutGentelella.cshtml";
}

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Add New Player</title>
    <link href="~/Content/css/icheck/flat/green.css" rel="stylesheet">
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <link href="~/Content/themes/base/datepicker.css" rel="stylesheet" />
    <style>
        .error {
            color: #ef5350;
        }
    </style>
</head>
<body>

    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">

            <div class="page-title">
                <div class="title_left">
                    <h3>New City</h3>
                </div>
            </div>


            @using (Html.BeginForm("NewCity", "PlayerMaster",
                FormMethod.Post,
                 new { enctype = "multipart/form-data", @class = "form-horizontal form-label-left", style = "margin-right:200px; margin-top:60px;" }))

            {

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Select Country<span class="required">*</span></label>
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.DropDownListFor(a => a.country_id, ViewBag.country as List<SelectListItem>, "--Select Country--", new { @class = "select2_single form-control", required="required" })
                        @Html.ValidationMessageFor(a => a.country_id, "", new { @class = "error" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">New City<span class="required">*</span></label>
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.TextBoxFor(a => a.city_name, new { @class = "form-control col-md-7 col-xs-12", type = "text", name = "txtSkill", @autocomplete = "off", required = "true" })
                    </div>
                </div>

                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <button type="reset" class="btn btn-primary">Cancel</button>
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </div>
            }

            @if (ViewBag.Success_City == false)
            {
                <div class="alert alert-error alert-dismissable fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Error!</strong> Fill in the required details!
                </div>
            }

            @if (ViewBag.Success_City_Validate == false)
            {
                <div class="alert alert-error alert-dismissable fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Error!</strong> Entered City already exists!
                </div>
            }

            @if (ViewBag.Added_City == true)
            {
                <div class="alert alert-info alert-dismissable fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Success!</strong> New City Added Successfully!
                </div>
            }

        </div>
    </div>


</body>
</html>


