IPLAuction/Controllers/Master/NewTeamController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using IPLAuction.Models;
using System;
using IPLAuction.Models.Extended;
using System.IO;
using System.Threading.Tasks;

namespace IPLTrial.Controllers
{
    public class NewTeamController : Controller
    {

        IPLEntities ipl = new IPLEntities();
        TeamUtility util = new TeamUtility();

        public ActionResult AddNewTeam()
        {
            //Populating cities in dropdown 
            ViewBag.cities = util.GetCityHostWise();

            //Populating owners in dropdown
            ViewBag.owners = util.GetOwner();

            ViewBag.coaches = util.GetCoaches();

            Response.Cache.SetNoStore();

            using (var context = new IPLEntities())
            {

                ViewBag.count_matches = context.match_master.ToList().Count;
                ViewBag.count_players = context.player_master.ToList().Count;
                ViewBag.count_teams = context.team_master.ToList().Count;

                int id = Convert.ToInt32(System.Web.HttpContext.Current.Session["userID"]);
                if (id != 0)
                {
                    ViewBag.user_id = id;

                    string user_name = System.Web.HttpContext.Current.Session["user_name"].ToString();
                    ViewBag.user_name = user_name;
                    TempData["user_name"] = ViewBag.user_name;

                    string user_type = System.Web.HttpContext.Current.Session["user_type"].ToString();
                    ViewBag.user_type = user_type;
                    TempData["user_type"] = ViewBag.user_type;

                    ViewBag.user_image = System.Web.HttpContext.Current.Session["user_image"];
                    TempData["user_image"] = ViewBag.user_image;

                }
            }

            return View();
        }

        public JsonResult getVenue(int id)
        {
           List<SelectListItem> venue =  util.GetVenueList(id);
            return Json(new SelectList(venue, "Value", "Text", JsonRequestBehavior.AllowGet));
        }
        
        [HttpPost]
        public ActionResult AddNewTeam(team_master team, FormCollection form, System.Web.HttpPostedFileBase fileUpload, string txtBudget, team_budget team_budget)
        {
            string budget = "0";

            if (!ModelState.IsValid || fileUpload == null)
            {
                ViewBag.Success = false;
                ViewBag.cities = util.GetCity();
                ViewBag.owners = util.GetOwner();
                ViewBag.coaches = util.GetCoaches();
                return View();
            }
            ViewBag.cities = util.GetCity();
            ViewBag.owners = util.GetOwner();
            ViewBag.coaches = util.GetCoaches();

            string id = form["venue"].ToString();

            if (id == null || id == "--Select Homeground--")
            {
                ViewBag.Success = false;
                ViewBag.cities = util.GetCity();
                ViewBag.owners = util.GetOwner();
                ViewBag.coaches = util.GetCoaches();
                return View();
            }
            team.homeground = Int32.Parse(id);

            if (fileUpload != null && fileUpload.ContentLength > 0)
            {
                //extract file name
                var fileName = Path.GetFileName(fileUpload.FileName);
                //store the file inside ~/App_Data/uploads folder
                var path = Path.Combine(Server.MapPath("~/uploads/"), fileName);
                fileUpload.SaveAs(path);

                

                if (ModelState.IsValid)
                {
                    if (ipl.team_master.Any(a => a.team_name == team.team_name))
                    {
                        ViewBag.Validate = false;
                        return View();
                    }

                    team.team_logo = Url.Content("~/uploads/" + fileName);
                    TempData["team_logo"] = team.team_logo;
                    TempData.Keep("team_logo");
                    budget = Request.Form["txtBudget"];

                    team.team_founded = DateTime.Now;
                    ipl.team_master.Add(team);

                    ipl.SaveChanges();

                    int team_id = team.team_id;
                    string team_name = team.team_name;

                    var season = ipl.season_master.Max(s => s.season_year);
                    var season_id = ipl.season_master.Where(a => a.season_year == season).FirstOrDefault();
                    team_budget.season_id = season_id.season_id;
                    team_budget.team_id = team_id;
                    team_budget.total_budget = Convert.ToDecimal(budget);
                    ipl.team_budget.Add(team_budget);
                    ipl.SaveChanges();

                    TempData["team_id"] = team_id;
                    TempData.Keep("team_id");
                    TempData["team_name"] = team_name;
                
                    TempData["team_success"] = true;
                    TempData.Keep("team_succcess");
                   
                    return RedirectToAction("TeamSquad", "TeamSquad");
                }
                
            }
            return View();
        }

        public interface HttpPostedFileBase
        {
            int Length { get; }
            object ContentDisposition { get; }
            string FileName { get; }

            Stream OpenReadStream();
            void SaveAs(string physicalPath);
            Task SaveAsAsync(string v);
        }

    }
}
    

IPLAuction/Views/NewTeam/AddNewTeam.cshtml
@model IPLAuction.Models.Validation.team_masterMetaType
@{
    ViewBag.Title = "AddNewTeam";
     Layout = "~/Views/Shared/_LayoutGentelella.cshtml";
}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Add New Team</title>
    <link href="~/Content/css/icheck/flat/green.css" rel="stylesheet">
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <link href="~/Content/themes/base/datepicker.css" rel="stylesheet" />
    <style>
        .error {
            color: red;
        }
    </style>
    <style type="text/css">
        #inr {
            float: right;
            margin-right: 6px;
            margin-top: -20px;
            position: relative;
            z-index: 2;        }
    </style>
</head>
<body>
    <script type="text/javascript">

    $(document).ready(function () {

        $("#city").change(function () {
            $("#venue").empty();
            $("#venue").append('<option value="' + "" + '">' +
                "--Select Homeground--" + '</option>');

            $.ajax({
                type: 'POST',
                url: '@Url.Action("getVenue")',
                dataType: 'json',
                data: { id: $("#city").val() },
                success: function (venues) {
                    $.each(venues, function (i, venue) {
                        $("#venue").append('<option value="' + venue.Value + '">' +
                             venue.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        })
    });

    </script>
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">

            <div class="page-title">
                <div class="title_left">
                    <h3>New Team</h3>
                </div>
            </div>

            @using (Html.BeginForm("AddNewTeam", "NewTeam",
                                        FormMethod.Post,
                                         new { enctype = "multipart/form-data", @class = "form-horizontal form-label-left", style = "margin-right:200px; margin-top:60px;" }))

            {

                <div class="form-group">
                    @Html.LabelFor(a => a.team_name, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.TextBoxFor(a => a.team_name, new { @class = "form-control col-md-7 col-xs-12", type = "text", @autocomplete = "off", required = "required" })
                        @Html.ValidationMessageFor(a => a.team_name, "", new { @class = "error" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(a => a.team_short_code, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.TextBoxFor(a => a.team_short_code, new { @class = "form-control col-md-7 col-xs-12", type = "text", @autocomplete = "off", required = "required" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(a => a.coach_id, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.DropDownListFor(a => a.coach_id, ViewBag.coaches as List<SelectListItem>, "--Select Coach--", new { @class = "select2_single form-control", @id = "coach", required = "required" })
                        @Html.ValidationMessageFor(a => a.coach_id, "", new { @class = "error" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(a => a.homecity, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.DropDownListFor(a => a.homecity, ViewBag.cities as List<SelectListItem>, "--Select City--", new { @class = "select2_single form-control", @id = "city", required = "required" })
                        @Html.ValidationMessageFor(a => a.homecity, "", new { @class = "error" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Home Ground<span class="required">*</span></label>
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.DropDownList("venue", new SelectList("", "Value", "Text"), "--Select Homeground--", new { @class = "select2_single form-control", required = "required" })
                        @Html.ValidationMessage("Select homeground", new { @class = "error" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(a => a.owner_id, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.DropDownListFor(a => a.owner_id, ViewBag.owners as List<SelectListItem>, "--Select Owner--", new { @class = "select2_single form-control", required = "required" })
                        @Html.ValidationMessageFor(a => a.owner_id, "", new { @class = "error" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(a => a.active, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        @Html.RadioButtonFor(a => a.active, true, new { @class = "flat", @checked = "checked" })
                        <label for="Active">Active</label>

                        @Html.RadioButtonFor(a => a.active, false, new { @class = "flat" })
                        <label for="Inactive">Inactive</label><br />
                        @Html.ValidationMessageFor(a => a.active, "", new { @class = "error" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Team Budget<span class="required">*</span></label>
                    <div class="col-md-4 col-sm-4 col-xs-6">
                     <input type="text" name="txtBudget" class="form-control" required="required" autocomplete="off" placeholder="Team Budget" /><span class="fa fa-inr" id="inr"></span>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(a => a.team_logo, new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="col-md-4 col-sm-4 col-xs-6">
                        <input type="file" name="fileUpload" class="form-control col-md-7 col-xs-12" />
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <button type="reset" class="btn btn-primary">Cancel</button>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            }
            @if (ViewBag.Success == false)
            {
                <div class="alert alert-error alert-dismissable fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Error!</strong> Fill in the required fields!
                </div>
            }
            @if (ViewBag.Validate == false)
            {
                <div class="alert alert-error alert-dismissable fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Error!</strong> Team with same name already exists!
                </div>
            }
        </div>
    </div>
    <!-- / Page Content-->
</body>

</html>